databases:
  - name: task-manager-db
    plan: free
    databaseName: task_manager

services:
  - type: web
    plan: free
    name: task-manager
    env: node
    buildCommand: make build
    startCommand: make start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-db
          property: connectionString
